on:
    push:
        branches: [master]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Setup .NET Core
          uses: actions/setup-dotnet@v1
          with: 
              dotnet-version: 3.1
        - name: Dotnet Publish
          run: dotnet publish 'DU Audio Test 2' -c Release -o AudioSharp --self-contained --runtime win-x64
        - name: Zip files
          uses: thedoctor0/zip-release@master
          with:
              filename: './AutoBuild.zip'
              exclusions: '*.git* /*node_modules/* .editorconfig'
              path: ./AudioSharp
        - name: Create github Release
          id: create_release
          uses: actions/create-release@v1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              tag_name: Auto-build
              release_name: Auto-build
              draft: true
              prerelease: false
        - name: Remove old release
          uses: dev-drprasad/delete-tag-and-release@v0.2.0
          with: 
              delete_release: true
              tag_name: Auto-build
          env: GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Upload release
          uses: actions/upload-release-asset@v1.0.1
          env: 
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with: 
              upload_url: ${{ steps.create_release.outputs.upload_url }}
              asset_path: ./AutoBuild.zip
              asset_name: AutoBuild.zip
              asset_content_type: application/zip
        - name: Publish release
          uses: eregon/publish-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            release_id: ${{ steps.create_release.outputs.id }}